name: CI Testing

on:
  pull_request:
    branches:
      - main

jobs:
  package_bulk:
    name: Package Bulk Limitations
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 20.6.1
    - run: npm run limits

  linter:
    name: Code Linter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 20.6.1
    - run: npm install
    - run: npm run lint

  package-report:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 20.6.1
    - run: npm pack --dry-run 2>&1 | sed 's/npm notice //g'
#    - run: |
#        {
#          echo 'NPM_PACK_RESULTS<<EOF'
#          npm pack --dry-run 2>&1 | sed 's/npm notice //g' | sed 's/\$/\\n/g' | tr -d'\\n'
#          echo EOF
#        } >> "$GITHUB_ENV"
#      id: packresults
#    - uses: actions/github-script@v6
#      with:
#        script: |
#          github.rest.issues.createComment({
#            issue_number: context.issue.number,
#            owner: context.repo.owner,
#            repo: context.repo.repo,
#            body: "${{ steps.packresults.outputs.NPM_PACK_RESULTS }}"
#          })


  test:
    name: Specific Node.js version
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 12.17.0 # no dc, first with AsyncLocalStorage
          - 12.x # no dc, last 12
          - 14.0.0 # no dc, first 14
          - 14.16.x # last without dc
          - 14.17.0 # introduces dc
          - 14.18.x # last without ch.unsubscribe return
          - 14.19.0 # introduces ch.unsubscribe return
          - 14.x # nothing special, has dc, last 14
          - 15.0.0 # first/last without dc
          - 15.1.0 # introduces dc
          - 15.x # nothing special, has dc, last 15
          - 16.0.0 # introduces dc
          - 16.13.x # last without ch.unsubscribe return
          - 16.14.0 # introduces ch.unsubscribe return
          - 16.16.x # last without dc.subscribe/unsubscribe
          - 16.17.0 # introduces dc.subscribe/unsubscribe
          - 16.x # nothing special, has dc, latest 16
          - 17.0.0 # first 17, last without ch.unsubscribe return
          - 17.1.0 # introduces ch.unsubscribe return
          - 17.x # nothing special, has dc, last 17
          - 18.0.0 # introduces dc
          - 18.6.x # last without dc.subscribe/unsubscribe
          - 18.7.0 # introduces dc.subscribe/unsubscribe
          - 18.18.x # last without TC
          - 18.19.0 # first with TC
          - 18.x # nothing special, has dc, latest 18
          - 19.0.0 # nothing special, has dc
          - 19.8.x # nothing special, has dc
          - 19.9.0 # https://github.com/nodejs/node/pull/47520
          - 20.0.0 # first 20
          - 20.5.1 # sync unsubscribe bug
          - 20.6.0 # sync unsubscribe bug fixed
          - 20.x # nothing special, latest 20
          - 20.12.x # last version without TC early exit and TC#hasSubscribers()
          - 20.13.0 # introduces TC early exit and TC#hasSubscribers()
          - 21.0.0 # nothing special, first 21
          - 21.x # nothing special, latest 21
          - 22.0.0 # introduces TC early exit and TC#hasSubscribers()
          - 22.x # nothing special, full support DC
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm test
