name: CI Testing

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Specific Node.js version
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 12.x # no dc, last 12
          - 14.0.0 # no dc, first 14
          - 14.16.x # last without dc
          - 14.17.0 # introduces dc
          - 14.18.x # last without ch.unsubscribe return
          - 14.19.0 # introduces ch.unsubscribe return
          - 14.x # nothing special, has dc, last 14
          - 15.0.0 # first/last without dc
          - 15.1.0 # introduces dc
          - 15.x # nothing special, has dc, last 15
          - 16.0.0 # introduces dc
          - 16.13.x # last without ch.unsubscribe return
          - 16.14.0 # introduces ch.unsubscribe return
          - 16.16.x # last without dc.subscribe/unsubscribe
          - 16.17.0 # introduces dc.subscribe/unsubscribe
          - 16.x # nothing special, has dc, latest 16
          - 17.0.0 # first 17, last without ch.unsubscribe return
          - 17.1.0 # introduces ch.unsubscribe return
          - 17.x # nothing special, has dc, last 17
          - 18.0.0 # introduces dc
          - 18.6.x # last without dc.subscribe/unsubscribe
          - 18.7.0 # introduces dc.subscribe/unsubscribe
          - 18.x # nothing special, has dc, latest 18
          - 19.0.0 # nothing special, has dc
          - 19.8.x # nothing special, has dc
          - 19.9.0 # https://github.com/nodejs/node/pull/47520
          - 20.0.0 # should support everything
          - 20.x # nothing special, full support dc, latest 20
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm test

  package_bulk:
    name: Package Bulk Limitations
    runs-on: ubuntu-latest
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 20.6.1
    - run: npm run limits
