name: git-ci-build

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 12.x # no dc, last 12
          - 14.0.0 # no dc, first 14
          - 14.16.1 # last without dc
          - 14.17.0 # introduces dc
          - 14.x # nothing special, last 14
          - 15.0.0 # first/last without dc
          - 15.1.0 # introduces dc
          - 15.x # nothing special, last 15
          - 16.0.0 # introduces dc
          - 16.16.0 # last without dc.subscribe/unsubscribe
          - 16.17.0 # introduces dc.subscribe/unsubscribe
          - 16.x # nothing special, latest 16
          - 17.0.0 # nothing special, first 17
          - 17.x # nothing special, last 17
          - 18.0.0 # introduces dc
          - 18.6.0 # last without dc.subscribe/unsubscribe
          - 18.7.0 # introduces dc.subscribe/unsubscribe
          - 18.x # nothing special, latest 18
          - 20.0.0 # should support everything
          - 20.x # nothing special, latest 20
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm test
